project:
  type: book
  output-dir: docs
  
book:
  title: "The JASP Data Library"
  author: "The JASP Team"
  date: today
  chapters:
    - index.qmd
  sidebar:
    contents:
      - index.qmd
      - auto: "myChapters/chapter*"

bibliography: references.bib

format:
  html:
    theme: bootstrap
  pdf:
    documentclass: scrreprt

editor: visual
new_session: no
url_sanitize: false
