name: UpdateDL

on:
  push:
      branches: ["main"]
  workflow_dispatch:
  schedule:
      # every day at 5&19 UTC
      - cron:  '0 14 * * 1'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: fetch jasp-desktop
        uses: actions/checkout@v4
        with:
          repository: jasp-stats/jasp-desktop
          ref: development
          path: jasp-desktop
      - name: checkout main
        uses: actions/checkout@v4
        with:
          path: datalib        
      - name: Run script
        run: |
          python datalib/.scripts/dataGatherScript.py jasp-desktop datalib
      - name: GIT add,commit and push all changed files to main
        continue-on-error: true
        env: 
          CI_COMMIT_MESSAGE: Automated push
          CI_COMMIT_AUTHOR: Actions
        run: |
          cd datalib
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add -A
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
